name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Toit build environment
        uses: ./toit/actions/setup-build
        with:
          toit-dir: toit
          esp32: true # Install build tools for ESP32

      - shell: bash
        run: echo $PATH

      - name: Build
        shell: bash
        run: |
          make